### PR TITLE
fix: switched to yarn since npm fails to install pnpm on arm64v8

### PR DESCRIPTION
**Pull request by markus-li**
Once I ran multi-platform builds I noticed that there was a failure for arm64v8.

### CODE REVIEW

**Comment by cyberalien** [comment]
Not a fan of yarn. This repo doesn't really use any extra functionality from pnpm, so maybe just switch to npm?

**Comment by markus-li** [comment]
since you have a pnpm lock file I wanted to keep using that, yarn in this case is only used to install pnpm, not for anything else.

**Comment by cyberalien** [comment]
Switched repository to npm. It doesn't make any difference for this repo.

**Comment by markus-li** [comment]
Ok, I'll switch to npm for docker as well then. Just need to make sure updating of npm works in all platforms.
I've run tests with having yarn removed after installing pnpm and that worked as well. I'll keep that one in mind for the future.

**Comment by cyberalien** [comment]
Merged. Thanks!

**Pull request merged**
